services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: elatmor
      DB_PASS: w3uRU[{0960n
      DB_NAME: elatmor_db
      PORT: 3000
      CLOUDINARY_CLOUD_NAME: dv4enxyxo
      CLOUDINARY_API_KEY: 964321319365178
      CLOUDINARY_API_SECRET: VA9YILM1doEIcCpXPwZMrSk8bAQ
      PAYMOB_API_KEY: ZXlKaGJHY2lPaUpJVXpVeE1pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmpiR0Z6Y3lJNklrMWxjbU5vWVc1MElpd2ljSEp2Wm1sc1pWOXdh$
      PAYMOB_SECRET_KEY: egy_sk_live_706fccc91d8f2d3ad42fd61b28dd99f550f435318c0c57cf3bb55dc849d9b9b0
      PAYMOB_PUBLIC_KEY: egy_pk_live_mPI3bAsuoEjeZDcqNfWotMc6KcDIUga1
      PAYMOB_INTEGRATION_ID: 5261462
      PAYMOB_INTEGRATION_ID_WALLET: 5261461
      PAYMOB_IFRAME_ID: 875103
      PAYMOB_HMAC_SECRET: 9D9B6EACB69C3045F83B17E5F1D6DC60
    ports:
      - "3398:3000"
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "9720:3000"
    restart: unless-stopped

  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: elatmor
      POSTGRES_PASSWORD: w3uRU[{0960n
      POSTGRES_DB: elatmor_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5396:5432"
    restart: unless-stopped

volumes:
  postgres_data:
